Metrics/LineLength:
  Max: 80
  Exclude:
    - 'spec/**/*_spec.rb'
Metrics/MethodLength:
  Max: 15
Metrics/ClassLength:
  Max: 100
EndOfLine:
  Enabled: false
Style/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'
AllCops:
  Exclude:
    - 'file_data.gemspec'